# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Choice_Scores',
            new_name='Service_Choice_Score',
        ),
    ]
