# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170423_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_identifier',
            field=models.CharField(default='skills1', max_length=10),
            preserve_default=False,
        ),
    ]
