# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170424_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=40, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_posted',
            field=models.DateField(verbose_name='Erstellugsdatum'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.TextField(verbose_name='Persönliche Nachricht'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=40, verbose_name='Beruf'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='PLZ'),
        ),
    ]
