# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170424_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True, verbose_name='Persönliche Nachricht'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=40, verbose_name='Beruf'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer'),
        ),
    ]
