# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170424_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(upload_to='/static/images/'),
        ),
    ]
