# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 08:26
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20170501_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='static'), upload_to='services'),
        ),
    ]
