# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_profile_empty_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empty_profile',
            field=models.BooleanField(default=False),
        ),
    ]
