# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_profile_empty_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='empty_profile',
            field=models.BooleanField(default=False, verbose_name='Dummyprofil'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_subtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=80),
        ),
    ]
