# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20170615_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
        migrations.AddField(
            model_name='profile',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Bearbeitungsnotizen'),
        ),
    ]
