# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20170615_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned',
            field=models.CharField(blank=True, max_length=100, verbose_name='Im Einsatz bei'),
        ),
    ]
