# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'offen'), ('accepted', 'aufgenommen'), ('cancelled', 'abgebrochen')], default=('open', 'offen'), max_length=30, verbose_name='Status'),
        ),
    ]
